# This is a workflow to help building sphinx-documentation

name: time-profiler

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    paths:
    - src/mex/**
    - src/profiling/**
  pull_request:
    branches:
    - main


  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and commit doc changes
    # Publish built docs to gh-pages branch.
    # ===============================
      run: |
        docker run -v $(pwd):/datos --entrypoint /bin/bash --rm caroacostatovany/optimizacion-2-practica-2-parte-2:0.1 -c "export PATH=$PATH:/home/miuser/.local/bin/ && cd /datos/reports && pip install -e . && cd .."
        git config user.name ${{ secrets.GH_USER }}
        git config user.email "${{ secrets.GH_MAIL }}"
        git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/:user/:repo.git"
        git fetch gh-token && git fetch gh-token main:main
        kernprof -l -v src/profiling/tiempo/net_line_profiler.py >> reports/net_profiling.txt
        git push gh-token main
