# This is a workflow to help building sphinx-documentation

name: time-profiler

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    paths:
    - src/mex/**
    - src/profiling/**
  pull_request:
    branches:
    - main


  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and commit doc changes
    # Publish built docs to gh-pages branch.
    # ===============================
      run: |
        mkdir reports/profiling && chmod gou+wrx -R reports
        docker run -v $(pwd):/datos --entrypoint /bin/bash --rm caroacostatovany/optimizacion-2-practica-2-parte-2:0.1 -c "export PATH=$PATH:/home/miuser/.local/bin/ && cd /datos/reports && pip install -e . && cd ../src/profiling/tiempo && kernprof -l -v " net_line_profiler.py >> net_profile.txt

    - name: Time profiling
      uses: peaceiris/actions-time-profiling@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/
